# Generated by Django 2.0.5 on 2018-09-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Please describe the task', max_length=3000)),
                ('created', models.DateField(auto_now_add=True)),
                ('language', models.CharField(choices=[('Android', 'android'), ('Python', 'python'), ('Other', 'other')], default='other', max_length=30)),
            ],
        ),
    ]
