# Generated by Django 2.0.5 on 2018-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='subject',
            field=models.CharField(help_text='Please provide a brief subject', max_length=255),
        ),
    ]
