# Generated by Django 2.0.5 on 2018-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180917_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskrequest',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(max_length=250, unique=True, upload_to='profiles'),
        ),
    ]
